
spring.profiles.active=dev
spring.application.name=sistema-de-chaves
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
spring.datasource.url=${DB_URL}

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
